### ISSUE TITLE
JSON-SERVER command error

### ISSUE THREAD

**Issue by dvalvarenga** [leoobarbosa2/ifood-clone#3]
Oi ! tudo bem ? 

Primeiramente parabéns e obrigado por compartilhar o código.
Não estou conseguindo rodar o comando 
json-server --host 192.168.11.16 -p 3333 -w 

Ele pede como argumento o arquivo JSON como src para a api.
Pode indicar aonde está o arquivo json ou poderia compartilhar o seu arquivo de exemplo ?

Obrigado

**Comment by andermarcebr** [comment]
Pois é, aqui pra mim apareceu a mesma coisa, estou tentando resolver aqui, se conseguir informo. abcs

**Comment by andermarcebr** [comment]
opa, consegui resolver amigo, só colocar o nome do arquivo server.json no final, ficando assim:
json-server --host 192.168.11.16  -p 3333 -w server.json

onde vc trocaria o 192.168.11.16 pelo seu ip 

espedo que dê certo ai pra vc...

abcs

**Comment by JbBorgesJr** [comment]
o meu não quer funcionar nem com "json-server --host 192.168.11.16 -p 3333 -w server.json"

**Comment by leoobarbosa2** [comment]
o @andermarcebr  entrou em contato comigo pra avisar mesmo ..

Na verdade aqui na minha máquina eu rodo o comando da seguinte forma `json-server --host 192.168.11.16 -p 3333 server.json  -w `

Mas como foi comentado, você precisa trocar o IP, para o ip da sua máquina, o exemplificado no README é com o IP da minha máquina
